### ISSUE TITLE
Add support for Literata

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium-css#58]
I'm submitting a feature request.

**Short description of the issue/suggestion:**

Literata is a high quality font for long form reading designed initially for Google Play Books: https://github.com/googlefonts/literata

It was recently open sourced and would make a wonderful addition to Readium CSS and test apps.

**Comment by JayPanoz** [comment]
You mean, in docs (https://github.com/readium/readium-css/blob/master/docs/CSS10-libre_fonts.md) or in RCSS itself? → 

Right now, the only fonts we’re “embedding” are the a11y-specific fonts, see. https://github.com/readium/readium-css/tree/master/css/dist/fonts

**Comment by HadrienGardeur** [comment]
What's your take on this? 

I think it might be worth extending font embedding to a subset of fonts from various families that we could vouch for.

**Comment by JayPanoz** [comment]
Hmmm as far as I can remember, there’s been 2 major factors “preventing” us from embedding fonts until now: 

1. font updates – some fonts are regularly updated so recommending them and pointing to their repo was the easy way out;
2. technical constraints on some platforms – I can recall a discussion @ EDRLab during which we discussed that in the i18n context, some fonts supporting Japanese being 10 MB for instance, and some size limit popped up, which is why we turned to downloadable fonts, see https://github.com/readium/r2-testapp-kotlin/issues/12.

In any case I must test it with [our own tool](https://readium.org/readium-css/docs/utils/Typeface-tester.html) though, to make sure it is rendered properly on all platforms – it’s not yet available on Google Fonts so that’s quite a significant signal to take into account. 

So I’m definitely not against a subset of fonts we could vouch for but the 2 constraints are tricky to say the least – kerning, hinting, support, etc. can be improved dramatically on updates so we probably want to avoid updating the repo every time a font is updated.

**Comment by JayPanoz** [comment]
Hmmm interesting, I’m running into various issues at least on MacOS with the old deliverables (both OTF and TTF). 

Safari will simply refuse to render it, Chrome is OK, some glyphs are buggy in Firefox (esp. Cyrillic + Greek). All latest versions. 

I’d recommend we wait for google fonts to upload it as you must currently build latest from the repo’s src in order to check if those issues are resolved. 

Here’s the generated report from Chrome, looking good in terms of support and OT features though. 

![capture d ecran 2019-01-23 a 13 14 47](https://user-images.githubusercontent.com/12599652/51606000-ee550d80-1f10-11e9-814b-ffb37d456d32.png)

And comparison with Georgia:

![capture d ecran 2019-01-23 a 13 07 35](https://user-images.githubusercontent.com/12599652/51606023-06c52800-1f11-11e9-89aa-54649bf07133.png)

**Comment by JayPanoz** [comment]
So yeah it looks like I have a system-wide issue with user-installed local fonts in Mojave (MacOS 10.14.2). Those fonts appears OK everywhere, including word processors, DTP apps, etc., except Safari.

So this is not about Literata. 

![capture d ecran 2019-01-23 a 23 34 20](https://user-images.githubusercontent.com/12599652/51642026-35bab880-1f68-11e9-8472-efe905ac37fb.png)

As every user-installed local font I’m testing fails. 

![capture d ecran 2019-01-23 a 23 38 04](https://user-images.githubusercontent.com/12599652/51642052-466b2e80-1f68-11e9-8563-b732f688ed12.png)

![capture d ecran 2019-01-23 a 23 38 13](https://user-images.githubusercontent.com/12599652/51642053-49661f00-1f68-11e9-8bbd-e4ca959f49f3.png)

![capture d ecran 2019-01-23 a 23 38 34](https://user-images.githubusercontent.com/12599652/51642056-4c610f80-1f68-11e9-9b19-0802ebe9b692.png)

Those ones worked when I made the md doc, and they’re still working otherwise. I’ve tried a simple webpage and could get the same result. 

Preinstalled (system) local fonts are OK: 

![capture d ecran 2019-01-23 a 23 44 23](https://user-images.githubusercontent.com/12599652/51642273-ea54da00-1f68-11e9-98c3-d315828fd305.png)

User-installed local fonts are also OK in Chrome and Firefox: 

![capture d ecran 2019-01-23 a 23 34 25](https://user-images.githubusercontent.com/12599652/51642105-79152700-1f68-11e9-86de-cc804e0935da.png)

![capture d ecran 2019-01-23 a 23 34 49](https://user-images.githubusercontent.com/12599652/51642108-7dd9db00-1f68-11e9-89d9-34e55481b0dd.png)

However, Firefox has an issue with some glyphs e.g. "ϐ" and "ϕ": 

![capture d ecran 2019-01-23 a 23 35 58](https://user-images.githubusercontent.com/12599652/51642164-977b2280-1f68-11e9-9347-f548b355e7de.png)

Those are OK in Chrome: 

![capture d ecran 2019-01-23 a 23 35 50](https://user-images.githubusercontent.com/12599652/51642209-b8dc0e80-1f68-11e9-982a-974e63ee65a6.png)

**Comment by JayPanoz** [comment]
So research tells me Safari nuked user-installed local fonts because of fingerprinting (tracking). 

If you're using `local` in a `font-face` declaration even, it will consequently use an online source.

**Comment by matt-curtis** [comment]
I stumbled across this issue by chance, but one solution might be to establish a local server that proxies requests for those user-installed fonts.

**Comment by JayPanoz** [comment]
@HadrienGardeur I’m postponing this a little more I’m afraid. 

They added a list of required changes to the GitHub repo yesterday: https://github.com/googlefonts/literata/blob/master/NOTES_JS.txt and there’s still no sign of it on Google Fonts, even on Early Access – so my assumption is that they don’t feel it can be distributed yet.

**Comment by HadrienGardeur** [comment]
Literata is now available on Google Fonts: https://fonts.google.com/specimen/Literata

Might be worth revisiting this issue?

**Comment by JayPanoz** [comment]
Ah yes thanks for spotting the availability. 

I’ll add to docs first, but re. 

> I think it might be worth extending font embedding to a subset of fonts from various families that we could vouch for.

I guess this is probably a good candidate for next week’s call? What do people think?
