### ISSUE TITLE
Shouldn't the publisher's defaults be enabled by default?

### ISSUE THREAD

**Issue by mickael-menu** [readium/readium-css#78]
The `advanced-settings` property is set to `readium-advanced-on` by default, [according to the documentation](https://github.com/readium/readium-css/blob/master/docs/CSS19-api.md), and this is reflected in the mobile apps. But shouldn't the publisher's default styles be enabled by default instead?

**Comment by JayPanoz** [comment]
Ah thanks for pointing this. 

The doc is confusing indeed, as “default” means the default value that is expected for it to work when present on the root element (so it maps to the [ReadiumCSS-config](https://github.com/readium/readium-css/blob/master/css/ReadiumCSS-config.css)).

Then it’s up to implementers to pick whether they want it to be the default for all EPUB reflowable publications, or the ones who have only been customised via user prefs, etc.

But looking at this doc confused me as well moments ago, so I’ll try to clarify.

**Comment by mickael-menu** [comment]
Okay I see, so it's something to be fixed in the navigator then. Thanks!

**Comment by JayPanoz** [comment]
Yeah you can think of those flags as “boolean inline styles.” So 

```
--USER__advancedSettings: "readium-advanced-on"
```

equals `true`. And other values equal `false`.

I can’t say they’re behaving like the [boolean attributes in HTML](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) because it’s not the case: their enabling/disabling indeed depends on the `value`.

I’ll have to recheck the entire docs to see if we’re event talking about real defaults for these flags though, in case there’s a conflict.
