### ISSUE TITLE
Width and height safeguards hide audio controls + video

### ISSUE THREAD

**Issue by JayPanoz** [readium/readium-css#94]
Submitting a bug report that was discovered by @aferditamuriqi 

**Short description of the issue/suggestion:**

There is a rendering issue with `audio` and `video` because of `width: auto` and `height: auto` in this declaration (should also impact the vertical writing version of the module).

https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/src/modules/ReadiumCSS-safeguards.css#L48-L69

For instance, in this screenshot, there should be audio controls:

<img width="1529" alt="screen_shot_2020-09-07_at_10 42 55_am" src="https://user-images.githubusercontent.com/12599652/92401114-50d24000-f12d-11ea-8a95-f210b4940628.png">

And when you disable `width` and `height` in dev tools, they are displayed correctly:

<img width="1554" alt="screen_shot_2020-09-07_at_10 42 49_am" src="https://user-images.githubusercontent.com/12599652/92401142-5f205c00-f12d-11ea-8e69-cd1942eeecab.png">

Given these can be useful for other media e.g. `img`, `audio` + `video` should be moved to their own specific declaration. If we want to safeguard the sizing and fall back to the browser’s default, it seems we can use the `revert` value:

<img width="1543" alt="screen_shot_2020-09-07_at_10 58 36_am" src="https://user-images.githubusercontent.com/12599652/92401575-3c427780-f12e-11ea-9125-3de39247c307.png">

This should be fixed quickly as it’s a high priority bug.

**Comment by danielweck** [comment]
Duplicate issue moved: https://github.com/readium/readium-css/issues/100

Problematic CSS:
https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/src/modules/ReadiumCSS-safeguards.css#L52-L53

I have an EPUB constructed from a set of webpages, notably this one (scroll down to see the audio elements):

http://diagramcenter.org/diagram-reports/diagram-report-2019/sonification.html

As tested in Thorium, ReadiumCSS applies `auto` to the `width` and `height` properties, resulting in a `0px` CSS box (i.e. invisible audio element despite the `controls` attribute).

I fixed this problem by adding the following to the author stylesheet:

```css
audio {
width: 100%;
height: 2em;
}
```

I would have preferred to use `inherit` or `initial` in order to avoid "hard coding" property values (especially the `em` value) ... but this didn't work in the Web Inspector (Chromium).

Any idea of why `auto` breaks things?

**Comment by danielweck** [comment]
Update: in Thorium we now inject the following CSS `<style>` element immediately after ReadiumCSS "before" external `<link>` stylesheet (which is first in the HTML `head`), therefore before any authored styles:

```css
audio[controls] {
width: revert;
height: revert;
}
```

**Comment by JayPanoz** [comment]
Proposal: add Daniel’s snippet to the safeguards module.
