### ISSUE TITLE
Text rendering issue with readium's css

### ISSUE THREAD

**Issue by rahulk11** [readium/readium-css#95]
I am having issue with readium css in r2 test app for some epubs. 
The text is overlapping in some cases and in some cases text on top is getting cropped.
I have included the screenshots for all the cases and also from readium1 test app(SDKLauncher-Android)
It mostly works fine in readium1.
### **Case: publisher's default turned off**
**1.** 
<img width="270" alt="publisher's default turned off1" src="https://user-images.githubusercontent.com/6279327/95712963-5b7b7a00-0c83-11eb-870f-6c91d5f5580a.png">
**2.** 
<img width="270" alt="publisher's default turned off2" src="https://user-images.githubusercontent.com/6279327/95712971-5e766a80-0c83-11eb-98f2-40b428cce7c2.png">
**3.** 
<img width="270" alt="publisher's default turned off3" src="https://user-images.githubusercontent.com/6279327/95712978-61715b00-0c83-11eb-9478-3b72d226315e.png">

### **Case: publisher's default turned on**
**1.** 
<img width="270" alt="publisher's default turned on1" src="https://user-images.githubusercontent.com/6279327/95712988-66cea580-0c83-11eb-8f73-bb010e69defd.png">
**2.** 
<img width="270" alt="publisher's default turned on2" src="https://user-images.githubusercontent.com/6279327/95712994-6930ff80-0c83-11eb-8732-21f1edacef90.png">
**3.** 
<img width="270" alt="publisher's default turned on3" src="https://user-images.githubusercontent.com/6279327/95713006-6f26e080-0c83-11eb-8119-5c48746b9c2d.png">

### **Case: Readium1 Test App**
**1.** 
<img width="270" alt="readium1_test_app1" src="https://user-images.githubusercontent.com/6279327/95713032-7bab3900-0c83-11eb-833e-51fc9856d1d3.png">
**2.** 
<img width="270" alt="readium1_test_app2" src="https://user-images.githubusercontent.com/6279327/95713036-7c43cf80-0c83-11eb-94b1-2b9203af2988.png">
**3.** 
<img width="270" alt="readium1_test_app3" src="https://user-images.githubusercontent.com/6279327/95713044-7f3ec000-0c83-11eb-82d2-91cae0c414c1.png">

**Comment by danielweck** [comment]
Hello, can the problem be reproduced consistently in all R2 target platforms? (iOS, Android and desktop/Electron)

**Comment by rahulk11** [comment]
Hi, yes, the issue is reproducible in iOS as well as thorium - r2 based desktop app.

This is in iOS
![CA44CA4E-6447-4E03-80C0-BC6E236C17BB_20201012_140501924.jpg](https://user-images.githubusercontent.com/6279327/95724390-f11f0580-0c93-11eb-83d3-4426e91b345b.jpg)

And this in thorium
![Screenshot 2020-10-12 at 12.09.41 PM_20201012_135952916.jpg](https://user-images.githubusercontent.com/6279327/95724442-0136e500-0c94-11eb-8142-58115eb92b04.jpg)

**Comment by JayPanoz** [comment]
This indeed is a side-effect of disabling publisher’s settings as we then apply a font-normalisation to handle font-size. That font-normalisation exists because we don’t have a universal way/API to handle font-size in browsers, on all platforms, and a significant percentage of EPUB files would have otherwise broken the font-size setting due to the usage of absolute units. It’s the best we can do in CSS due to the lack of such standard feature.

This should serve as a use-case for #34 though, because we’ve been willing to strongly emphasise that if a native font-size API/method is available on a particular platform, it should be used in lieu of Readium CSS’ font-normalisation.

**Comment by rahulk11** [comment]
@JayPanoz Hi, There are issues also with the publisher's default ON. Check above screenshots . The texts are overlapping.

**Comment by JayPanoz** [comment]
Thanks for your patience. 

I’ll have to coordinate with @danielweck and @mickael-menu on this one, as I’m not sure what is exactly going on in the apps. 

So as a recap, these headings are `p` with `classes`, which is the reason the impact with publisher’s default off is so huge – should these be `h1`, `h2`, etc. it would already solve some rendering issues with advanced settings. That’s also why the chapter heading – which is using a `table` with a negative bottom margin for layout purposes – ends up being cut off with publisher’s default off. 

Anyways. 

**Thorium:** 

I am able to consistently reproduce these rendering issues with the test app as well when enabling settings, but they disappear w/o any issue when re-enabling publisher’s default. I can also tell they happen because `readium-advanced-on` is set on the `root`  element (+ `text-align`).

What I don’t understand is why it stays there after a single setting change, @danielweck? Or does its removal not trigger a relayout? 

**Android + iOS:**

So this overlapping text with publisher’s default on left me dumbfounded to be honest. Technically, ReadiumCSS does set a `line-height` on `html` just in case, knowing the vast majority of authors’ stylesheets will override that value further down the DOM (`body`, `h1`, `p`, etc.). This is not the case with this EPUB. 

It should also be large enough that this overlapping doesn’t happen, and I can’t really understand the discrepancy between Android and iOS so I’ll need @mickael-menu’s help on this one.

Android: it clearly overlaps.

![Screenshot_20201023-104618](https://user-images.githubusercontent.com/12599652/96977209-0e1dc900-151d-11eb-8025-4934e6800bea.png)

iOS: it’s close, mind you, but it doesn’t.

![Photo 23-10-2020 10 15 41](https://user-images.githubusercontent.com/12599652/96977028-d020a500-151c-11eb-988b-837ce5b39f23.png)

There difference might be explained by the computed value of `line-height` for `html` and/or if it is inherited by this `p`? At first I thought that maybe it could be a bug in Chrome re. font metrics but having tested the iOS test app I’m not so sure now. 

In passing, such “freeform” heading should really really set a `line-height`, because there is no guarantee the default will be the same in all apps – in some, users can even change this default.
